language: java

before_install:
  - chmod +x gradlew
  # Amazon JDK -- https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source install-jdk.sh --url https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.tar.gz
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version

script:
  - ls -laRh
  - printenv
  - ./gradlew projects clean build jacocoTestReport --no-daemon --refresh-dependencies

after_success:
  - bash <(curl -s https://codecov.io/bash)
